/* empty css                           */import { b as createAstro, c as createComponent, r as renderTemplate, m as maybeRenderHead, d as addAttribute, a as renderSlot, e as renderComponent, u as unescapeHTML } from '../astro_f852e106.mjs';
import 'clsx';
import { c as company_name, t as tag_line, $ as $$Paragraph, d as description, a as $$Container, b as $$Title, s as services, e as $$BtnLink, f as about_us, m as mission_short, v as vision_short, g as $$Layout } from './about_23618e10.mjs';
import 'html-escaper';
/* empty css                           */
const $$Astro$2 = createAstro();
const $$Button = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$2, $$props, $$slots);
  Astro2.self = $$Button;
  const { className, variant } = Astro2.props;
  const getThemeStyle = (variant2) => {
    if (variant2 === "primary") {
      return "bg-primary border-transparent relative after:bg-[#172554] hover:border-[#172554]";
    }
    return "text-primary";
  };
  return renderTemplate`${maybeRenderHead()}<button${addAttribute(`px-6 py-3 rounded-full outline-none relative overflow-hidden border duration-300 ease-linear
                    after:absolute after:inset-x-0 after:aspect-square after:scale-0 after:opacity-70 after:origin-center after:duration-300 after:ease-linear after:rounded-full after:top-0 after:left-0 after:bg-[#172554]
                    ${getThemeStyle(variant)} hover:after:opacity-100 hover:after:scale-[2.5] ${className}`, "class")}> ${renderSlot($$result, $$slots["default"])} </button>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/shared/Button.astro", void 0);

const $$Hero = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<section class="relative pt-32 lg:pt-36"> ${renderComponent($$result, "Container", $$Container, { "className": "flex flex-col lg:flex-row gap-10 lg:gap-12" }, { "default": ($$result2) => renderTemplate` <div class="absolute w-full lg:w-1/2 inset-y-0 lg:right-0 "> <span class="absolute -left-6 md:left-4 top-24 lg:top-28 w-24 h-24 rotate-90 skew-x-12 rounded-3xl bg-green-400 blur-xl opacity-60 lg:opacity-95 lg:block hidden"></span> <span class="absolute right-4 bottom-12 w-24 h-24 rounded-3xl bg-primary blur-xl opacity-80"></span> </div> <span class="w-4/12 lg:w-2/12 aspect-square bg-gradient-to-tr from-primary to-green-400 absolute -top-5 lg:left-0 rounded-full skew-y-12 blur-2xl opacity-40 skew-x-12 rotate-90"></span> <div class="relative flex flex-col items-center text-center lg:text-left lg:py-7 xl:py-8 
        lg:items-start lg:max-w-none max-w-3xl mx-auto lg:mx-0 lg:flex-1 lg:w-1/2"> <h1 class="text-3xl/tight sm:text-4xl/tight md:text-5xl/tight xl:text-6xl/tight
             font-bold text-heading-1"> ${company_name}<span class="text-transparent bg-clip-text bg-gradient-to-br from-indigo-600 from-20% via-primary via-30% to-green-600"><p></p>${tag_line}</span> </h1> ${renderComponent($$result2, "Paragraph", $$Paragraph, { "className": "mt-8" }, { "default": ($$result3) => renderTemplate`${description}` })} <div class="mt-10  w-full flex max-w-md mx-auto lg:mx-0"> <div class="flex sm:flex-row flex-col gap-5 w-full"> <form action="#" class="py-1 pl-6 w-full pr-1 flex gap-3 items-center text-heading-3 shadow-lg shadow-box-shadow
                      border border-box-border bg-box-bg rounded-full ease-linear focus-within:bg-body  focus-within:border-primary"> <span class="min-w-max pr-2 border-r border-box-border"> <svg xmlns="http://www.w3.org/2000/svg" width="20" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"> <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 9v.906a2.25 2.25 0 01-1.183 1.981l-6.478 3.488M2.25 9v.906a2.25 2.25 0 001.183 1.981l6.478 3.488m8.839 2.51l-4.66-2.51m0 0l-1.023-.55a2.25 2.25 0 00-2.134 0l-1.022.55m0 0l-4.661 2.51m16.5 1.615a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V8.844a2.25 2.25 0 011.183-1.98l7.5-4.04a2.25 2.25 0 012.134 0l7.5 4.04a2.25 2.25 0 011.183 1.98V19.5z"></path> </svg> </span> <input type="email" name="" id="" placeholder="johndoe@gmail.com" class="w-full py-3 outline-none bg-transparent"> ${renderComponent($$result2, "Button", $$Button, { "variant": "primary", "className": "min-w-max text-white" }, { "default": ($$result3) => renderTemplate` <span class="hidden sm:flex relative z-[5]">
Get Started
</span> <span class="flex sm:hidden relative z-[5]"> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"> <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5"></path> </svg> </span> ` })} </form> </div> </div> </div> <div class="flex flex-1 lg:w-1/2 lg:h-auto relative lg:max-w-none lg:mx-0 mx-auto max-w-3xl"> <img src="/images/image1.gif" alt="Hero image" width="2350" height="2359" class="lg:absolute lg:w-full lg:h-full rounded-3xl object-cover lg:max-h-none max-h-96"> </div> ` })} <!-- <ByNumber/> --> </section>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/sections/Hero.astro", void 0);

const $$Astro$1 = createAstro();
const $$Service = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$Service;
  const { title, description, icon } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<div class="p-5 sm:p-6 lg:p-8 rounded-3xl border border-box-border bg-box-bg shadow-lg shadow-box-shadow relative overflow-hidden"> <div class="rounded-xl bg-gray-300 dark:bg-gray-950 p-3 text-heading-1 w-max relative"> ${renderSlot($$result, $$slots["default"], renderTemplate`${unescapeHTML(icon)}`)} </div> <div class="mt-6 space-y-4 relative"> <h2 class="text-lg md:text-xl font-semibold text-heading-2"> ${title} </h2> ${renderComponent($$result, "Paragraph", $$Paragraph, {}, { "default": ($$result2) => renderTemplate`${description}` })} </div> <span class="absolute w-32 aspect-square -bottom-16 -right-16 bg-primary/10 rounded-full"></span> </div>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/cards/Service.astro", void 0);

const $$Services = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<section id="services"> ${renderComponent($$result, "Container", $$Container, { "className": "space-y-10 md:sapce-y-12" }, { "default": ($$result2) => renderTemplate` <div class="text-center max-w-3xl mx-auto space-y-4"> ${renderComponent($$result2, "Title", $$Title, {}, { "default": ($$result3) => renderTemplate` Current Projects ` })} ${renderComponent($$result2, "Paragraph", $$Paragraph, {}, { "default": ($$result3) => renderTemplate` Our current exciting projects. ` })} </div> <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8"> ${services.slice(0, 3).map((service) => {
    return renderTemplate`${renderComponent($$result2, "Service", $$Service, { "title": service.title, "description": service.description, "icon": service.icon })}`;
  })} </div> <div class="lg:min-w-max flex items-center sm:w-max w-full pb-6 lg:pb-0 border-b border-box-bg lg:border-0 px-6 lg:px-0"> ${renderComponent($$result2, "BtnLink", $$BtnLink, { "href": "/projects", "text": "View all projects", "variant": "primary", "className": "min-w-max text-white" })} </div> ` })} </section>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/sections/Services.astro", void 0);

const $$Astro = createAstro();
const $$Info = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Info;
  const { title, description } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<div class="p-5 sm:p-6 lg:p-8 rounded-3xl border border-box-border bg-box-bg shadow-lg shadow-box-shadow relative overflow-hidden"> <div class="rounded-xl bg-gray-300 dark:bg-gray-950 p-3 text-heading-1 w-max relative"> ${renderSlot($$result, $$slots["icon"])} </div> <h2 class="md:text-xl font-semibold text-heading-2 mt-6 mb-4"> ${title} </h2> ${renderComponent($$result, "Paragraph", $$Paragraph, {}, { "default": ($$result2) => renderTemplate`${description}` })} </div>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/cards/Info.astro", void 0);

const $$AboutUs = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<section id="about-us"> ${renderComponent($$result, "Container", $$Container, { "className": "flex flex-col midmd:flex-row gap-10 lg:gap-12" }, { "default": ($$result2) => renderTemplate` <div class="max-w-md mx-auto midmd:max-w-none lg:mx-0 lg:pr-10 xl:pr-2 flex-1 flex w-11/12 midmd:w-5/12 lg:w-1/2 midmd:h-auto"> <div class="w-full h-80 sm:h-96 midmd:h-full relative"> <div class="absolute rotate-45 -left-5 md:-left-10 lg:-left-20 xl:-left-24 p-1 top-1/2 w-16 h-16 bg-gradient-to-br from-primary to-orange-400 blur-3xl opacity-50"></div> <div class="absolute p-1 -top-4 md:-top-10 right-0 w-20 h-20 bg-gradient-to-br from-primary to-orange-400 rounded-full blur-3xl opacity-60"></div> <span class="absolute w-full aspect-[16/5] -skew-x-12 rounded-full bg-gradient-to-tr from-primary to-green-400 opacity-40 blur-2xl left-0 bottom-0"></span> <img${addAttribute("/images/image2.jpg", "src")} alt="banner image" width="1240" height="1385" class="w-auto left-1/2 -translate-x-1/2 absolute top-0 max-h-full rounded-md"> </div> </div> <div class="flex-1 flex midmd:w-7/12 lg:w-1/2 flex-col"> ${renderComponent($$result2, "Title", $$Title, {}, { "default": ($$result3) => renderTemplate` About us ` })} ${renderComponent($$result2, "Paragraph", $$Paragraph, { "className": "mt-8" }, { "default": ($$result3) => renderTemplate`${about_us}` })} <div class="pt-8 grid grid-cols-2 gap-4 max-w-3xl md:max-w-[none]"> ${renderComponent($$result2, "Info", $$Info, { "description": mission_short, "title": "Mission" }, { "icon": ($$result3) => renderTemplate`<span> <svg xmlns="http://www.w3.org/2000/svg" width="30" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 sm:w-5 sm:h-5"> <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z"></path> </svg> </span>` })} ${renderComponent($$result2, "Info", $$Info, { "description": vision_short, "title": "Vision" }, { "icon": ($$result3) => renderTemplate`<span> <svg xmlns="http://www.w3.org/2000/svg" width="30" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 sm:w-5 sm:h-5"> <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"></path> <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path> </svg> </span>` })} </div> <div class="lg:min-w-max mt-3 flex items-center sm:w-max w-full pb-6 lg:pb-0 border-b border-box-bg lg:border-0 px-6 lg:px-0"> ${renderComponent($$result2, "BtnLink", $$BtnLink, { "href": "/about", "text": "More about us", "variant": "primary", "className": "min-w-max text-white" })} </div> </div> ` })} </section>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/sections/AboutUs.astro", void 0);

const $$CTA = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<section id="cta" class="pb-20"> ${renderComponent($$result, "Container", $$Container, {}, { "default": ($$result2) => renderTemplate` <div class="w-full relative py-8 md:py-10 px-6 md:px-8 rounded-2xl bg-gradient-to-tr from-gray-100 to-gray-200 dark:from-gray-900"> <div class="absolute right-0 top-0 h-full w-full flex justify-end"> <div class="w-28 h-28 overflow-auto flex rounded-xl relative blur-2xl"> <span class="absolute w-16 h-16 -top-1 -right-1 bg-green-500 rounded-md rotate-45"></span> <span class="absolute w-16 h-16 -bottom-1 -right-1 bg-[#FCDC58] rounded-md rotate-45"></span> <span class="absolute w-16 h-16 -bottom-1 -left-1 bg-primary rounded-md rotate-45"></span> </div> </div> <div class="absolute left-0 bottom-0 h-full w-full flex items-end"> <div class="w-28 h-28 overflow-auto flex rounded-xl relative blur-2xl"> <span class="absolute w-16 h-16 -top-1 -right-1 bg-green-500 rounded-md rotate-45"></span> <span class="absolute w-16 h-16 -bottom-1 -right-1 bg-[#FCDC58] rounded-md rotate-45"></span> <span class="absolute w-16 h-16 -bottom-1 -left-1 bg-primary rounded-md rotate-45"></span> </div> </div> <div class="mx-auto text-center max-w-xl md:max-w-2xl relative"> <h1 class="text-3xl/tight sm:text-4xl/tight md:text-5xl/tight
          font-bold text-heading-1">
For <span class="text-transparent bg-clip-text bg-gradient-to-br from-indigo-600 from-20% via-primary via-30% to-green-600">Business</span> and <span class="text-transparent bg-clip-text bg-gradient-to-br from-indigo-600 from-20% via-primary via-30% to-green-600">Collaboration</span> </h1> ${renderComponent($$result2, "Paragraph", $$Paragraph, { "className": "pt-10" }, { "default": ($$result3) => renderTemplate`
We offer innovative solutions for your business needs, including drone development and customization. Our team of experts can help you leverage the power of drones to enhance your operations and achieve your goals.
` })} <div class="mx-auto max-w-md sm:max-w-xl pt-10"> ${renderComponent($$result2, "Button", $$Button, { "variant": "primary" }, { "default": ($$result3) => renderTemplate` <span class="text-white relative z-[5]">Get In Touch</span> ` })} </div> </div> </div> ` })} </section>`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/components/sections/CTA.astro", void 0);

const $$Index = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": company_name }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<main class="flex flex-col gap-y-20 md:gap-y-32 overflow-hidden"> ${renderComponent($$result2, "Hero", $$Hero, {})} <!-- <Brands/> --> ${renderComponent($$result2, "Services", $$Services, {})} ${renderComponent($$result2, "AboutUs", $$AboutUs, {})} <!-- <Features/> --> ${renderComponent($$result2, "CTA", $$CTA, {})} </main> ` })}`;
}, "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/pages/index.astro", void 0);

const $$file = "/Users/johnpaulparedes/Documents/GitHub/montemflumen/src/pages/index.astro";
const $$url = "";

export { $$Index as default, $$file as file, $$url as url };
